blueprint:
  name: Rauchmelder Alarm mit Notfallbestätigung
  description: >
    Rauchmelder-Blueprint mit drei Zuständen, Critical Alerts und Timeout.
    - Alarm ausgelöst: Lichter + Push
    - Notfall bestätigt: Aktionen nach Bestätigung oder Timeout
    - Fehlalarm: Aktionen nach Fehlalarm
  domain: automation
  input:
    smoke_detectors:
      name: Rauchmelder
      description: Welche Rauchmelder den Alarm auslösen
      selector:
        entity:
          domain: binary_sensor
          device_class: smoke
          multiple: true

    residents_group:
      name: Bewohner
      description: Geräte, die benachrichtigt werden
      selector:
        entity:
          domain: device_tracker
          multiple: true

    alarm_triggered_lights:
      name: Alarm ausgelöst – Lichter
      description: Lichter, die beim Alarm aktiviert werden
      selector:
        target:
          entity:
            domain: light

    emergency_confirmed_lights:
      name: Notfall bestätigt – Lichter
      description: Lichter für den Modus Notfall bestätigt
      selector:
        target:
          entity:
            domain: light

    false_alarm_lights:
      name: Fehlalarm – Lichter
      description: Lichter für den Modus Fehlalarm
      selector:
        target:
          entity:
            domain: light

    alarm_timeout:
      name: Zeit bis automatische Notfallbestätigung
      description: Zeit in Minuten, nach der der Alarm automatisch als Notfall bestätigt gilt
      default: 5
      selector:
        number:
          min: 1
          max: 60
          unit_of_measurement: minutes

automation:
  - alias: Rauchmelder Alarm
    trigger:
      - platform: state
        entity_id: !input smoke_detectors
        to: 'on'
    action:
      # Alarm ausgelöst Aktionen
      - service: light.turn_on
        target: !input alarm_triggered_lights

      # Push Benachrichtigung mit Critical Alert und Buttons
      - service: notify.mobile_app
        data:
          target: !input residents_group
          message: "🚨 Rauchmelder Alarm! Bitte wählen:"
          data:
            push:
              category: "critical_alert"
            actions:
              - action: "EMERGENCY_CONFIRMED"
                title: "Notfall bestätigen"
              - action: "FALSE_ALARM"
                title: "Fehlalarm"

      # Warten auf Benutzerinteraktion oder Timeout
      - wait_for_trigger:
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: EMERGENCY_CONFIRMED
          - platform: event
            event_type: mobile_app_notification_action
            event_data:
              action: FALSE_ALARM
        timeout: "{{ !input alarm_timeout * 60 }}"
        continue_on_timeout: true

      # Ausführen der Modus-Aktionen basierend auf der Aktion oder Timeout
      - choose:
          # Timeout → automatisch Notfall bestätigt
          - conditions:
              - condition: template
                value_template: >
                  {% set last_action = wait.trigger %}
                  {{ last_action is none }}
            sequence:
              - service: light.turn_on
                target: !input emergency_confirmed_lights
              - service: notify.mobile_app
                data:
                  target: !input residents_group
                  message: "✅ Notfall automatisch bestätigt (Timeout)!"
                  data:
                    push:
                      category: "critical_alert"

          # Notfall bestätigt manuell
          - conditions:
              - condition: event
                event_type: mobile_app_notification_action
                event_data:
                  action: EMERGENCY_CONFIRMED
            sequence:
              - service: light.turn_on
                target: !input emergency_confirmed_lights
              - service: notify.mobile_app
                data:
                  target: !input residents_group
                  message: "✅ Notfall bestätigt!"
                  data:
                    push:
                      category: "critical_alert"

          # Fehlalarm
          - conditions:
              - condition: event
                event_type: mobile_app_notification_action
                event_data:
                  action: FALSE_ALARM
            sequence:
              - service: light.turn_on
                target: !input false_alarm_lights
              - service: notify.mobile_app
                data:
                  target: !input residents_group
                  message: "⚠️ Fehlalarm!"
                  data:
                    push:
                      category: "critical_alert"