blueprint:
  name: "Feueralarm Automation 🔥"
  description: >
    Umfassender Feueralarm-Blueprint für Home Assistant. 
    Unterstützt Alarm-Modi, Testmodus (voll/selektiv), Präsenzlogik, Personengruppen, Push, Lichter/Szenen, TTS, konfigurierbare Entitäten, Rauchmelder-Synchronisation, Eskalationslogik, Logging/Dashboard und Notfallmodus.
  domain: automation
  input:
    # -----------------------------
    # 1️⃣ Alarm-Modi
    # -----------------------------
    alarm_mode:
      name: "Alarmmodus"
      description: "Initialer Alarmmodus"
      default: "Kein Alarm ✅"
      selector:
        select:
          options:
            - "Kein Alarm ✅"
            - "Alarm aktiv 🚨"
            - "Notfall bestätigt 🆘"
            - "Fehlalarm ❌"

    # -----------------------------
    # 2️⃣ Testmodus
    # -----------------------------
    test_mode:
      name: "Testmodus aktivieren 🧪"
      description: "Aktiviere Testmodus"
      default: false
      selector:
        boolean: {}

    test_mode_duration:
      name: "Testmodus Dauer"
      description: "Wie lange der Testmodus aktiv bleibt"
      default: "00:30:00"
      selector:
        duration: {}

    test_mode_full_program:
      name: "Volles Testprogramm"
      description: "Führt alle Aktionen wie im echten Alarm aus"
      default: true
      selector:
        boolean: {}

    # -----------------------------
    # 3️⃣ Präsenz-Erkennung
    # -----------------------------
    presence_sensors:
      name: "Präsenzsensoren 👥"
      description: "Binary Sensoren für Bewegung/Türen/Fenster"
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    persons:
      name: "Personen zu Hause"
      description: "Personen-Entities"
      selector:
        entity:
          domain: person
          multiple: true

    # -----------------------------
    # 4️⃣ Personengruppen
    # -----------------------------
    residents_group:
      name: "Bewohner 👪"
      selector:
        entity:
          domain: group
    emergency_contacts:
      name: "Notfallkontakte 👪"
      selector:
        entity:
          domain: group

    # -----------------------------
    # 5️⃣ Push-Benachrichtigungen
    # -----------------------------
    push_service:
      name: "Push-Service 📲"
      selector:
        action:

    # -----------------------------
    # 6️⃣ Beleuchtung / Szenen
    # -----------------------------
    alarm_lights:
      name: "Alarm-Lichter 🔴"
      selector:
        entity:
          domain: light
          multiple: true

    escape_lights:
      name: "Fluchtweg 🟢"
      selector:
        entity:
          domain: light
          multiple: true

    emergency_lights:
      name: "Notfallbeleuchtung ⚪"
      selector:
        entity:
          domain: light
          multiple: true

    # -----------------------------
    # 7️⃣ TTS
    # -----------------------------
    tts_speakers:
      name: "TTS-Speaker 🗣️"
      selector:
        entity:
          domain: media_player
          multiple: true

    # -----------------------------
    # 8️⃣ Konfigurierbare Entitäten
    # -----------------------------
    custom_entities:
      name: "Konfigurierbare Entitäten ⚙️"
      selector:
        entity:
          multiple: true

    # -----------------------------
    # 9️⃣ Rauchmelder
    # -----------------------------
    smoke_detectors:
      name: "Rauchmelder 🌐"
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    smoke_buzzer_mode:
      name: "Buzzer-Modus"
      default: "buzzer_alarm"
      selector:
        select:
          options:
            - "buzzer_select"
            - "buzzer_alarm"
            - "buzzer_mute"

    # -----------------------------
    # 🔟 Eskalationslogik
    # -----------------------------
    escalation_delay:
      name: "Zeit bis Eskalation ⚠️"
      default: "00:02:00"
      selector:
        duration: {}

    # -----------------------------
    # 1️⃣1️⃣ Logging & Dashboard
    # -----------------------------
    logbook_entity:
      name: "Logbuch-Entity 📊"
      selector:
        entity:
          domain: input_text

    dashboard_entity:
      name: "Dashboard-Status-Entity"
      selector:
        entity:
          domain: input_text

    # -----------------------------
    # 1️⃣2️⃣ Notfallmodus
    # -----------------------------
    emergency_button:
      name: "Notfallmodus aktivieren 🏃‍♂️"
      selector:
        entity:
          domain: input_boolean

variables:
  alarm_active: "{{ states(alarm_mode) != 'Kein Alarm ✅' }}"
  anyone_home: >
    {{ states('persons') | selectattr('state','eq','home') | list | length > 0 }}
  test_active: "{{ is_state(test_mode, 'on') }}"

trigger:
  - platform: state
    entity_id: !input alarm_mode
  - platform: state
    entity_id: !input test_mode
  - platform: state
    entity_id: !input emergency_button
    to: "on"

condition: []

action:
  - choose:
      # -----------------------------
      # Testmodus aktiv
      # -----------------------------
      - conditions:
          - "{{ test_active }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ test_mode_full_program }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Testmodus: Alle Alarmaktionen aktiviert."
                  - service: !input push_service
                    data:
                      message: "Testmodus: Vollprogramm"
              - conditions: []
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id: !input alarm_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Testmodus: Selektive Aktionen"
                  - service: !input push_service
                    data:
                      message: "Testmodus: Selektiv"
          - delay: !input test_mode_duration
          - service: light.turn_off
            target:
              entity_id:
                - !input alarm_lights
                - !input escape_lights
                - !input emergency_lights
          - service: tts.google_say
            target:
              entity_id: !input tts_speakers
            data:
              message: "Testmodus beendet"

      # -----------------------------
      # Notfallmodus manuell
      # -----------------------------
      - conditions:
          - "{{ is_state(trigger.entity_id,'on') and trigger.entity_id == !input emergency_button }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                - !input alarm_lights
                - !input escape_lights
                - !input emergency_lights
          - service: tts.google_say
            target:
              entity_id: !input tts_speakers
            data:
              message: "Notfallmodus aktiviert!"
          - service: !input push_service
            data:
              message: "Notfallmodus aktiviert 🏃‍♂️"

      # -----------------------------
      # Normaler Alarmmodus
      # -----------------------------
      - conditions:
          - "{{ alarm_active and not test_active }}"
        sequence:
          - choose:
              - conditions:
                  - "{{ states(alarm_mode) == 'Alarm aktiv 🚨' }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Feueralarm! Bitte beachten Sie die Sicherheitsmaßnahmen."
                  - service: !input push_service
                    data:
                      message: "Alarm aktiv 🚨"
                  - repeat:
                      until:
                        - condition: state
                          entity_id: !input alarm_mode
                          state: "Notfall bestätigt 🆘"
                      sequence:
                        - delay: !input escalation_delay
                        - service: !input push_service
                          data:
                            message: "Eskalation: Alarm weiterhin aktiv 🚨"

              - conditions:
                  - "{{ states(alarm_mode) == 'Notfall bestätigt 🆘' }}"
                sequence:
                  - service: !input push_service
                    data:
                      message: "Notfall bestätigt 🆘"
                  - service: light.turn_on
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights

              - conditions:
                  - "{{ states(alarm_mode) == 'Fehlalarm ❌' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Fehlalarm aufgehoben."

mode: single