blueprint:
  name: Rauchmelder-Alarm mit Bestätigung & Sirenen-Mute
  description: >
    Rauchmelder-Alarm: Öffnet Rollläden, schaltet Lichter, sendet kritische Push-Benachrichtigung.
    Die Sirene (Buzzer) wird nach Bestätigung per App stummgeschaltet.
  domain: automation

  input:
    smoke_sensor:
      name: Rauchmelder
      description: Rauchmelder, der den Alarm auslöst.
      selector:
        entity:
          domain: binary_sensor
          device_class: smoke

    buzzer_select:
      name: Rauchmelder-Buzzer (Select)
      description: Die Select-Entität für die Sirene/Buzzer ("mute" Option).
      selector:
        entity:
          domain: select

    all_covers:
      name: Alle Rollläden öffnen
      selector:
        boolean: {}
      default: false

    target_covers:
      name: Ziel-Rollläden (nur ausfüllen, wenn "Alle Rollläden" aus)
      selector:
        target:
          entity:
            domain: cover
      default: []

    all_lights:
      name: Alle Lichter einschalten
      selector:
        boolean: {}
      default: false

    target_lights:
      name: Ziel-Lichter (nur ausfüllen, wenn "Alle Lichter" aus)
      selector:
        target:
          entity:
            domain: light
      default: []

    notify_devices:
      name: Mobilgeräte für Push-Nachricht
      selector:
        device:
          integration: mobile_app
          multiple: true

variables:
  action_ack: "ACKNOWLEDGE_ALARM"

trigger:
  - platform: state
    entity_id: !input smoke_sensor
    to: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input smoke_sensor
            state: "on"
        sequence:
          #
