blueprint:
  name: "Feueralarm Full Dashboard + Auto Buzzer 🔥"
  description: >
    Vollständiger Feueralarm-Blueprint mit automatischer Buzzer-Steuerung.
    Testmodus stumm, Normalalarm laut, Fehlalarm aus.
  domain: automation
  input:
    # Rauchmelder 🌐
    smoke_detectors:
      name: "🌐 Rauchmelder"
      description: "Alle zu überwachenden Rauchmelder"
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    # Lichter / Szenen 💡
    alarm_lights:
      name: "🚨 Alarm-Lichter"
      selector:
        entity:
          domain: light
          multiple: true
    escape_lights:
      name: "🟢 Fluchtweg-Lichter"
      selector:
        entity:
          domain: light
          multiple: true
    emergency_lights:
      name: "⚪ Notfall-Lichter"
      selector:
        entity:
          domain: light
          multiple: true

    # TTS 🗣️
    tts_speakers:
      name: "🗣️ TTS-Speaker"
      selector:
        entity:
          domain: media_player
          multiple: true

    # Konfigurierbare Entitäten ⚙️
    custom_entities:
      name: "⚙️ Rollos, Steckdosen, Smart Locks"
      selector:
        entity:
          multiple: true

    # Push / Notfallkontakte 📲
    push_service:
      name: "📲 Push-Service"
      selector:
        action:
    residents_group:
      name: "👪 Bewohner"
      selector:
        entity:
          domain: group
    emergency_contacts:
      name: "🆘 Notfallkontakte"
      selector:
        entity:
          domain: group

    # Notfallmodus / Testmodus 🏃‍♂️🧪
    emergency_button:
      name: "🏃‍♂️ Notfallmodus"
      selector:
        entity:
          domain: input_boolean
    test_mode:
      name: "🧪 Testmodus aktiv"
      selector:
        boolean: {}
    test_mode_duration:
      name: "⏱️ Testmodus Dauer"
      default: "00:00:30"
      selector:
        duration: {}
    test_mode_full_program:
      name: "⚡ Testmodus Vollprogramm"
      default: true
      selector:
        boolean: {}

    # Eskalation ⚠️
    escalation_delay:
      name: "⏳ Zeit bis Eskalation"
      default: "00:02:00"
      selector:
        duration: {}

    # Logging & Dashboard 📊
    logbook_entity:
      name: "📓 Logbuch"
      selector:
        entity:
          domain: input_text
    dashboard_entity:
      name: "📊 Dashboard"
      selector:
        entity:
          domain: input_text

    # Alarmmodus 🚨🆘❌
    alarm_mode:
      name: "🚨 Alarmmodus"
      default: "Kein Alarm ✅"
      selector:
        select:
          options:
            - "Kein Alarm ✅"
            - "Alarm aktiv 🚨"
            - "Notfall bestätigt 🆘"
            - "Fehlalarm ❌"

trigger:
  - platform: state
    entity_id: !input smoke_detectors
    to: "on"
  - platform: state
    entity_id: !input emergency_button
    to: "on"
  - platform: state
    entity_id: !input test_mode
    to: "on"
  - platform: state
    entity_id: !input alarm_mode

condition: []

action:
  # -----------------------------
  # Testmodus
  # -----------------------------
  - choose:
      - conditions:
          - "{{ is_state(test_mode,'on') }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: !input smoke_detectors
            data:
              option: "buzzer_mute"
          - service: light.turn_on
            target:
              entity_id:
                - !input alarm_lights
                - !input escape_lights
                - !input emergency_lights
          - service: tts.google_say
            target:
              entity_id: !input tts_speakers
            data:
              message: "Testmodus aktiviert"
          - service: !input push_service
            data:
              message: "Testmodus aktiv"
          - choose:
              - conditions: "{{ test_mode_full_program }}"
                sequence:
                  - service: cover.open_cover
                    target:
                      entity_id: !input custom_entities
          - delay: !input test_mode_duration
          - service: light.turn_off
            target:
              entity_id:
                - !input alarm_lights
                - !input escape_lights
                - !input emergency_lights
          - service: tts.google_say
            target:
              entity_id: !input tts_speakers
            data:
              message: "Testmodus beendet"

  # -----------------------------
  # Notfallmodus manuell
  # -----------------------------
      - conditions:
          - "{{ trigger.entity_id == !input emergency_button }}"
        sequence:
          - service: select.select_option
            target:
              entity_id: !input smoke_detectors
            data:
              option: "buzzer_alarm"
          - service: light.turn_on
            target:
              entity_id:
                - !input alarm_lights
                - !input escape_lights
                - !input emergency_lights
          - service: tts.google_say
            target:
              entity_id: !input tts_speakers
            data:
              message: "Notfallmodus aktiviert!"
          - service: !input push_service
            data:
              message: "Notfallmodus aktiviert"
          - service: cover.open_cover
            target:
              entity_id: !input custom_entities

  # -----------------------------
  # Normaler Alarm durch Rauchmelder
  # -----------------------------
      - conditions: []
        sequence:
          - service: select.select_option
            target:
              entity_id: !input smoke_detectors
            data:
              option: "buzzer_alarm"
          - choose:
              - conditions: "{{ states('persons') | selectattr('state','eq','home') | list | length > 0 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Feueralarm! Bitte beachten Sie die Sicherheitsmaßnahmen."
                  - service: !input push_service
                    data:
                      message: "Alarm aktiv 🚨"
                  - service: cover.open_cover
                    target:
                      entity_id: !input custom_entities
              - conditions: []
                sequence:
                  - service: !input push_service
                    data:
                      message: "Feueralarm ausgelöst, niemand zu Hause"
          - delay: !input escalation_delay
          - service: !input push_service
            data:
              message: "Eskalation: Alarm weiterhin aktiv"

  # -----------------------------
  # Fehlalarm / Notfall bestätigt
  # -----------------------------
      - conditions:
          - "{{ states(alarm_mode) in ['Fehlalarm ❌','Notfall bestätigt 🆘'] }}"
        sequence:
          - choose:
              - conditions: "{{ states(alarm_mode) == 'Fehlalarm ❌' }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: !input smoke_detectors
                    data:
                      option: "buzzer_mute"
                  - service: light.turn_off
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Fehlalarm aufgehoben"
                  - service: !input push_service
                    data:
                      message: "Fehlalarm ❌"
              - conditions: "{{ states(alarm_mode) == 'Notfall bestätigt 🆘' }}"
                sequence:
                  - service: select.select_option
                    target:
                      entity_id: !input smoke_detectors
                    data:
                      option: "buzzer_alarm"
                  - service: light.turn_on
                    target:
                      entity_id:
                        - !input alarm_lights
                        - !input escape_lights
                        - !input emergency_lights
                  - service: tts.google_say
                    target:
                      entity_id: !input tts_speakers
                    data:
                      message: "Notfall bestätigt 🆘"
                  - service: !input push_service
                    data:
                      message: "Notfall bestätigt 🆘"

mode: single