blueprint:
  name: Rauchmelder-Alarm mit Bestätigung & Sirenen-Mute (mit Gruppen)
  description: >
    Rauchmelder-Alarm mit gruppierter Eingabe: Rollläden, Lichter, Benachrichtigung, Sirenen-Mute
    und kritischer iOS Push mit Bestätigungs-Button.
  domain: automation

  input:
    smoke_sensor:
      name: Rauchmelder
      description: Rauchmelder, der den Alarm auslöst.
      selector:
        entity:
          domain: binary_sensor
          device_class: smoke

    buzzer_select:
      name: Rauchmelder-Buzzer (Select)
      description: Die Select-Entität für die Sirene/Buzzer ("mute" Option).
      selector:
        entity:
          domain: select

    covers_group:
      name: Rollladen-Steuerung
      description: Optionen zur Steuerung der Rollläden
      default_expandable: true
      input:
        all_covers:
          name: Alle Rollläden öffnen
          selector:
            boolean: {}
          default: false

        target_covers:
          name: Ziel-Rollläden (wenn nicht alle)
          selector:
            target:
              entity:
                domain: cover
          default: []

    lights_group:
      name: Licht-Steuerung
      description: Optionen zur Steuerung der Lichter
      default_expandable: true
      input:
        all_lights:
          name: Alle Lichter einschalten
          selector:
            boolean: {}
          default: false

        target_lights:
          name: Ziel-Lichter (wenn nicht alle)
          selector:
            target:
              entity:
                domain: light
          default: []

    notify_group:
      name: Benachrichtigungen
      description: Auswahl für kritische Push-Nachricht
      default_expandable: true
      input:
        notify_devices:
          name: Mobilgeräte für Push-Nachricht
          selector:
            device:
              integration: mobile_app
              multiple: true

variables:
  action_ack: "ACKNOWLEDGE_ALARM"

trigger:
  - platform: state
    entity_id: !input smoke_sensor
    to: "on"

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input smoke_sensor
            state: "on"
        sequence:
          # Rollläden öffnen (aus der covers_group)
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ !input covers_group.all_covers }}"
                sequence:
                  - service: cover
